name: Repository Dispatch
description: A simple action used for posting repository_dispatch events.

inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  token:
    description: Personal Access Token (PAT) used to post the repository_dispatch event.
    default: ${{ github.token }}
  event_type:
    description: The event_type that will be posted.
    default: "hello_world"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ inputs.token }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{ inputs.repository }}/dispatches \
        -d '{"event_type":"${{ inputs.event_type }}"}'

